// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TelegramAi.Backend.Infrastructure.Persistence;

#nullable disable

namespace TelegramAi.Backend.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TelegramAi.Backend.Domain.Content.ContentItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ContentKind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("contents", (string)null);
                });

            modelBuilder.Entity("TelegramAi.Backend.Domain.Content.ContentItem", b =>
                {
                    b.OwnsOne("TelegramAi.Backend.Domain.Content.ContentSummary", "Summary", b1 =>
                        {
                            b1.Property<Guid>("ContentItemId")
                                .HasColumnType("uuid");

                            b1.Property<string>("KeyPoints")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("summary_key_points");

                            b1.Property<string>("Language")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("summary_language");

                            b1.Property<string>("Provider")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("summary_provider");

                            b1.Property<string>("ShortSummary")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("summary_short_summary");

                            b1.Property<string>("Tags")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("summary_tags");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("summary_title");

                            b1.HasKey("ContentItemId");

                            b1.ToTable("contents");

                            b1.WithOwner()
                                .HasForeignKey("ContentItemId");
                        });

                    b.Navigation("Summary")
                        .IsRequired();
                });

            modelBuilder.Entity("TelegramAi.Backend.Domain.Content.ContentChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("CharEnd")
                        .HasColumnType("integer");

                    b.Property<int>("CharStart")
                        .HasColumnType("integer");

                    b.Property<Guid>("ContentItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ContentItemId", "Index")
                        .IsUnique();

                    b.ToTable("content_chunks", (string)null);
                });

            modelBuilder.Entity("TelegramAi.Backend.Domain.Content.ContentChunk", b =>
                {
                    b.HasOne("TelegramAi.Backend.Domain.Content.ContentItem", null)
                        .WithMany()
                        .HasForeignKey("ContentItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
